#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::index
logout:
  path: /logout


maison:
  path: /maison
  controller: App\Controller\MaisonController::index

captcha_routing:
    resource: "@CaptchaBundle/Resources/config/routing.yml"



activites:
  path: /activites
  controller: App\Controller\ActivitesController::index

